import { TERMINAL_KINDS, catalog } from "./catalog.js";
import { buildCircuitArtifacts } from "./artifacts.js";
import { firstControllerTerminalFor, projectController } from "./connectivity.js";
import { normalizeProject, serializeCircuitLabProject } from "./model.js";
import { runCircuitLabTest } from "./testBench.js";

function sanitizeIdentifier(value) {
  return String(value ?? "circuit_lab")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 48) || "circuit_lab";
}

function terminalNumber(terminalId) {
  const digital = String(terminalId ?? "").match(/^D(\d+)$/i);
  if (digital) return Number(digital[1]);
  const gpio = String(terminalId ?? "").match(/^GPIO(\d+)$/i);
  if (gpio) return Number(gpio[1]);
  return null;
}

function controllerOutput(terminal) {
  return terminal.kind === TERMINAL_KINDS.SIGNAL && terminal.capabilities?.includes("output") && !terminal.inputOnly;
}

function controllerInput(terminal) {
  return terminal.kind === TERMINAL_KINDS.SIGNAL && terminal.capabilities?.includes("input");
}

function componentsByRole(project, role) {
  return normalizeProject(project).components.filter((component) => catalog.getComponent(component.typeId)?.sim.role === role);
}

function servoBindings(project) {
  return componentsByRole(project, "servo")
    .map((servo) => {
      const def = catalog.getComponent(servo.typeId);
      const terminal = firstControllerTerminalFor(project, {
        componentId: servo.id,
        terminalId: def.sim.signalTerminal ?? "signal"
      }, controllerOutput);
      return terminal ? { servo, terminal, pin: terminalNumber(terminal.terminal.id) } : null;
    })
    .filter((item) => item && Number.isFinite(item.pin));
}

function ledBinding(project) {
  const led = componentsByRole(project, "led")[0];
  if (!led) return null;
  const def = catalog.getComponent(led.typeId);
  const terminal = firstControllerTerminalFor(project, {
    componentId: led.id,
    terminalId: def.sim.outputTerminal ?? "anode"
  }, controllerOutput);
  const pin = terminalNumber(terminal?.terminal?.id);
  return Number.isFinite(pin) ? { component: led, terminal, pin } : null;
}

function buttonBinding(project) {
  const button = componentsByRole(project, "button")[0];
  if (!button) return null;
  const def = catalog.getComponent(button.typeId);
  const terminal = firstControllerTerminalFor(project, {
    componentId: button.id,
    terminalId: def.sim.inputTerminal ?? "sense"
  }, controllerInput);
  const pin = terminalNumber(terminal?.terminal?.id);
  return Number.isFinite(pin) ? { component: button, terminal, pin } : null;
}

function motorDriverBinding(project) {
  const driver = componentsByRole(project, "motorDriver")[0];
  if (!driver) return null;
  const in1 = firstControllerTerminalFor(project, { componentId: driver.id, terminalId: "IN1" }, controllerOutput);
  const in2 = firstControllerTerminalFor(project, { componentId: driver.id, terminalId: "IN2" }, controllerOutput);
  const in1Pin = terminalNumber(in1?.terminal?.id);
  const in2Pin = terminalNumber(in2?.terminal?.id);
  return Number.isFinite(in1Pin) && Number.isFinite(in2Pin) ? { driver, in1Pin, in2Pin } : null;
}

function generateArduinoIno(project) {
  const servos = servoBindings(project);
  const led = ledBinding(project);
  const button = buttonBinding(project);
  const driver = motorDriverBinding(project);
  const lines = [
    "#include <Servo.h>",
    "",
    "// Generated by RoboStudio Circuit Lab. Verify wiring before applying external power."
  ];
  servos.forEach((binding, index) => {
    lines.push(`Servo servo${index + 1};`);
    lines.push(`const int SERVO_${index + 1}_PIN = ${binding.pin};`);
  });
  if (led) lines.push(`const int LED_PIN = ${led.pin};`);
  if (button) lines.push(`const int BUTTON_PIN = ${button.pin};`);
  if (driver) {
    lines.push(`const int DRIVER_IN1_PIN = ${driver.in1Pin};`);
    lines.push(`const int DRIVER_IN2_PIN = ${driver.in2Pin};`);
  }
  lines.push("", "void setup() {");
  if (led) lines.push("  pinMode(LED_PIN, OUTPUT);");
  if (button) lines.push("  pinMode(BUTTON_PIN, INPUT_PULLUP);");
  if (driver) {
    lines.push("  pinMode(DRIVER_IN1_PIN, OUTPUT);");
    lines.push("  pinMode(DRIVER_IN2_PIN, OUTPUT);");
    lines.push("  digitalWrite(DRIVER_IN1_PIN, LOW);");
    lines.push("  digitalWrite(DRIVER_IN2_PIN, LOW);");
  }
  servos.forEach((binding, index) => {
    lines.push(`  servo${index + 1}.attach(SERVO_${index + 1}_PIN);`);
    lines.push(`  servo${index + 1}.write(90);`);
  });
  lines.push("}", "", "void loop() {");
  if (button && led) {
    lines.push("  const bool active = digitalRead(BUTTON_PIN) == LOW;");
    lines.push("  digitalWrite(LED_PIN, active ? HIGH : LOW);");
  } else if (led) {
    lines.push("  digitalWrite(LED_PIN, LOW);");
  }
  if (driver) lines.push("  // Motor outputs stay disabled until you add an explicit, reviewed command.");
  if (servos.length) lines.push("  // Servos hold neutral; no autonomous sweep is generated.");
  lines.push("  delay(1000);");
  lines.push("}");
  return `${lines.join("\n")}\n`;
}

function sourceSymbol(value) {
  return String(value ?? "channel")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 48) || "CHANNEL";
}

function functionName(value, prefix = "set") {
  return `${prefix}_${String(value ?? "channel")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 40) || "channel"}`;
}

function generateLinkedArduinoIno(project, artifacts) {
  const rows = artifacts.pinMapRows ?? [];
  const servoRows = rows.filter((row) => row["signal type"] === "servo-pulse");
  const outputRows = rows.filter((row) => ["digital", "pwm", "step", "direction", "enable"].includes(row["signal type"]) && row.direction === "controller-to-device");
  const inputRows = rows.filter((row) => ["digital", "analog"].includes(row["signal type"]) && row.direction === "device-to-controller");
  const lines = [
    "#include <Servo.h>",
    "",
    "// Generated by RoboStudio Circuit Lab from validated semantic firmware channels.",
    "// Safe default: initialize outputs to neutral/disabled and do not run autonomous motion."
  ];
  for (const row of rows) {
    const pin = terminalNumber(row["controller terminal ID"]);
    if (Number.isFinite(pin)) lines.push(`const int ${sourceSymbol(row["firmware channel ID"])}_PIN = ${pin};`);
  }
  servoRows.forEach((row) => {
    lines.push(`Servo ${functionName(row["firmware channel ID"], "servo")};`);
  });
  lines.push("", "void setup() {");
  for (const row of outputRows) {
    lines.push(`  pinMode(${sourceSymbol(row["firmware channel ID"])}_PIN, OUTPUT);`);
    lines.push(`  digitalWrite(${sourceSymbol(row["firmware channel ID"])}_PIN, LOW);`);
  }
  for (const row of inputRows.filter((row) => row["signal type"] === "digital")) {
    lines.push(`  pinMode(${sourceSymbol(row["firmware channel ID"])}_PIN, INPUT_PULLUP);`);
  }
  for (const row of servoRows) {
    lines.push(`  ${functionName(row["firmware channel ID"], "servo")}.attach(${sourceSymbol(row["firmware channel ID"])}_PIN);`);
    lines.push(`  ${functionName(row["firmware channel ID"], "servo")}.write(90);`);
  }
  lines.push("}");
  for (const row of servoRows) {
    lines.push("", `void ${functionName(row["firmware channel ID"])}(int degrees) {`);
    lines.push("  const int safeDegrees = constrain(degrees, 0, 180);");
    lines.push(`  ${functionName(row["firmware channel ID"], "servo")}.write(safeDegrees);`);
    lines.push("}");
  }
  for (const row of outputRows) {
    lines.push("", `void ${functionName(row["firmware channel ID"])}(bool enabled) {`);
    lines.push(`  digitalWrite(${sourceSymbol(row["firmware channel ID"])}_PIN, enabled ? HIGH : LOW);`);
    lines.push("}");
  }
  for (const row of inputRows) {
    const returnType = row["signal type"] === "analog" ? "int" : "bool";
    const readCall = row["signal type"] === "analog"
      ? `analogRead(${sourceSymbol(row["firmware channel ID"])}_PIN)`
      : `digitalRead(${sourceSymbol(row["firmware channel ID"])}_PIN) == HIGH`;
    lines.push("", `${returnType} ${functionName(row["firmware channel ID"], "read")}() {`);
    lines.push(`  return ${readCall};`);
    lines.push("}");
  }
  lines.push("", "void loop() {");
  lines.push("  // Add explicit reviewed calls here after completing the physical checklist.");
  lines.push("  delay(1000);");
  lines.push("}");
  return `${lines.join("\n")}\n`;
}

function gpioMacro(pin) {
  return Number.isFinite(pin) ? `GPIO_NUM_${pin}` : "GPIO_NUM_NC";
}

function generateEspIdfMain(project) {
  const led = ledBinding(project);
  const button = buttonBinding(project);
  const ledMacro = gpioMacro(led?.pin);
  const buttonMacro = gpioMacro(button?.pin);
  return `#include <stdbool.h>
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#define LED_GPIO ${ledMacro}
#define BUTTON_GPIO ${buttonMacro}

void app_main(void) {
    if (LED_GPIO != GPIO_NUM_NC) {
        gpio_reset_pin(LED_GPIO);
        gpio_set_direction(LED_GPIO, GPIO_MODE_OUTPUT);
    }
    if (BUTTON_GPIO != GPIO_NUM_NC) {
        gpio_reset_pin(BUTTON_GPIO);
        gpio_set_direction(BUTTON_GPIO, GPIO_MODE_INPUT);
        gpio_pullup_en(BUTTON_GPIO);
    }

    while (true) {
        const bool button_active = BUTTON_GPIO != GPIO_NUM_NC && gpio_get_level(BUTTON_GPIO) == 0;
        if (LED_GPIO != GPIO_NUM_NC) {
            gpio_set_level(LED_GPIO, button_active);
        }
        vTaskDelay(pdMS_TO_TICKS(500));
    }
}
`;
}

export function generateCircuitLabSource(project, options = {}) {
  const normalized = normalizeProject(project);
  const artifacts = options.artifacts ?? buildCircuitArtifacts({
    circuitLabProject: normalized,
    robotDesign: options.robotDesign ?? null,
    mechatronicsBinding: options.mechatronicsBinding ?? null
  });
  const test = artifacts.test ?? runCircuitLabTest(normalized);
  const controller = projectController(normalized);
  const firmware = controller?.definition?.sim?.firmware ?? "arduino";
  const unsupportedFirmware = !["arduino", "espidf"].includes(firmware);
  const baseName = sanitizeIdentifier(normalized.name);
  const files = [];
  const binding = artifacts.binding ?? null;
  const hasBindingRecords = Boolean(
    (binding?.actuatorBindings?.length ?? 0) ||
    (binding?.sensorBindings?.length ?? 0) ||
    (binding?.firmwareChannels?.length ?? 0)
  );
  const semanticChannelsReady = artifacts.bindingValidation?.ok === true && (artifacts.pinMapRows?.length ?? 0) > 0;
  const linkedSourceReady = semanticChannelsReady && firmware !== "espidf";
  const semanticSourceUnsupported = semanticChannelsReady && firmware === "espidf";
  const sourceMode = linkedSourceReady
    ? "semantic robot channels"
    : semanticSourceUnsupported
      ? "standalone safe starter; ESP-IDF semantic channels are not emitted yet"
      : unsupportedFirmware
        ? `source export not available for ${firmware} controllers`
        : "standalone safe starter";
  if (unsupportedFirmware) {
    files.push({
      path: "UNSUPPORTED_CONTROLLER.md",
      content: [
        `# ${controller?.instance?.name ?? "Unsupported controller"}`,
        "",
        `RoboStudio can validate wiring for this controller, but source generation is not implemented for firmware target ${firmware}.`,
        "",
        "Use the pin map, BOM, harness, and checklist as build documentation only."
      ].join("\n")
    });
  } else if (firmware === "espidf") {
    files.push(
      { path: "CMakeLists.txt", content: `cmake_minimum_required(VERSION 3.16)\ninclude($ENV{IDF_PATH}/tools/cmake/project.cmake)\nproject(${baseName})\n` },
      { path: "main/CMakeLists.txt", content: `idf_component_register(SRCS "app_main.c" INCLUDE_DIRS ".")\n` },
      { path: "main/app_main.c", content: generateEspIdfMain(normalized) }
    );
  } else {
    files.push({ path: `${baseName}.ino`, content: linkedSourceReady ? generateLinkedArduinoIno(normalized, artifacts) : generateArduinoIno(normalized) });
  }
  files.push({
    path: "README.md",
    content: [
      `# ${normalized.name}`,
      "",
      "Generated by RoboStudio Circuit Lab.",
      "",
      `- Controller: ${controller?.instance?.name ?? "none"}`,
      `- Test result: ${test.ok ? "clear" : "blocking issues present"}`,
      `- Source mode: ${sourceMode}`,
      "",
      "This export is source-only. It was not built, flashed, executed, or hardware-tested by RoboStudio.",
      "",
      "## Circuit Test",
      ...test.issues.map((item) => `- ${item.severity.toUpperCase()}: ${item.message}`)
    ].join("\n")
  });
  files.push({ path: "circuit-lab-project.json", content: artifacts.files?.["circuit-lab-project.json"] ?? serializeCircuitLabProject(normalized) });
  for (const path of ["pin-map.csv", "bom.csv", "harness.csv", "build-checklist.md"]) {
    if (artifacts.files?.[path]) files.push({ path, content: artifacts.files[path] });
  }
  return {
    ready: Boolean(controller) && !unsupportedFirmware && test.summary.errors === 0 && (!hasBindingRecords || linkedSourceReady),
    target: firmware,
    files,
    test,
    artifacts
  };
}
