import JSZip from "jszip";
import { catalog, gpioNumber } from "./catalog.js";
import { runDrc } from "./drc.js";
import { normalizeCircuitDesign } from "./schema.js";
import {
  componentsBySimRole,
  connectedGroundForComponentPin,
  firstUsableGpioForComponentPin
} from "./pins.js";

function sanitizeIdentifier(value) {
  return String(value ?? "circuit")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 48) || "circuit";
}

function gpioMacro(pinId) {
  const number = gpioNumber(pinId);
  return Number.isFinite(number) ? `GPIO_NUM_${number}` : "GPIO_NUM_NC";
}

function preferredComponent(design, role, preferredId) {
  const components = componentsBySimRole(design, role);
  return components.find((component) => component.id === preferredId) ?? components[0] ?? null;
}

export function buildCircuitIr(design) {
  const normalized = normalizeCircuitDesign(design);
  const board = catalog.getBoard(normalized.board.id);
  const output = preferredComponent(normalized, "led", normalized.app.outputComponentId);
  const input = preferredComponent(normalized, "button", normalized.app.inputComponentId);
  const outputDef = output ? catalog.getComponent(output.componentId) : null;
  const inputDef = input ? catalog.getComponent(input.componentId) : null;
  const outputPin = output && outputDef
    ? firstUsableGpioForComponentPin(normalized, output.id, outputDef.sim.outputPin ?? "anode")
    : null;
  const inputPin = input && inputDef
    ? firstUsableGpioForComponentPin(normalized, input.id, inputDef.sim.inputPin ?? "a")
    : null;
  const inputReturnGrounded = input && inputDef
    ? Boolean(connectedGroundForComponentPin(normalized, input.id, inputDef.sim.returnPin ?? "b"))
    : false;
  const drc = runDrc(normalized);
  return {
    name: sanitizeIdentifier(normalized.name),
    displayName: normalized.name,
    target: normalized.target,
    boardId: normalized.board.id,
    boardName: board?.name ?? normalized.board.id,
    output: output && outputPin ? {
      componentId: output.id,
      componentName: output.name,
      gpio: gpioNumber(outputPin.pinId),
      pinId: outputPin.pinId
    } : null,
    input: input && inputPin ? {
      componentId: input.id,
      componentName: input.name,
      gpio: gpioNumber(inputPin.pinId),
      pinId: inputPin.pinId,
      activeLow: inputReturnGrounded
    } : null,
    blinkPeriodMs: Math.max(50, Number(normalized.app.blinkPeriodMs) || 500),
    drc
  };
}

function generateMainC(ir) {
  const ledMacro = ir.output ? gpioMacro(ir.output.pinId) : "GPIO_NUM_NC";
  const buttonMacro = ir.input ? gpioMacro(ir.input.pinId) : "GPIO_NUM_NC";
  const buttonActiveExpression = ir.input
    ? (ir.input.activeLow ? "gpio_get_level(BUTTON_GPIO) == 0" : "gpio_get_level(BUTTON_GPIO) != 0")
    : "false";
  const blinkTicks = Math.max(1, Math.round(ir.blinkPeriodMs));
  return `#include <stdbool.h>
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#define LED_GPIO ${ledMacro}
#define BUTTON_GPIO ${buttonMacro}
#define BLINK_PERIOD_MS ${blinkTicks}

static void configure_outputs(void) {
    if (LED_GPIO != GPIO_NUM_NC) {
        gpio_reset_pin(LED_GPIO);
        gpio_set_direction(LED_GPIO, GPIO_MODE_OUTPUT);
        gpio_set_level(LED_GPIO, 0);
    }
}

static void configure_inputs(void) {
    if (BUTTON_GPIO != GPIO_NUM_NC) {
        gpio_reset_pin(BUTTON_GPIO);
        gpio_set_direction(BUTTON_GPIO, GPIO_MODE_INPUT);
        gpio_pullup_en(BUTTON_GPIO);
        gpio_pulldown_dis(BUTTON_GPIO);
    }
}

void app_main(void) {
    configure_outputs();
    configure_inputs();

    bool blink_state = false;
    while (true) {
        const bool button_active = ${buttonActiveExpression};
        blink_state = !blink_state;
        if (LED_GPIO != GPIO_NUM_NC) {
            gpio_set_level(LED_GPIO, button_active ? 1 : (blink_state ? 1 : 0));
        }
        vTaskDelay(pdMS_TO_TICKS(BLINK_PERIOD_MS));
    }
}
`;
}

function generateReadme(ir) {
  const lines = [
    `# ${ir.displayName}`,
    "",
    "Generated by RoboStudio Electronics.",
    "",
    `- Target: ${ir.target}`,
    `- Board: ${ir.boardName}`,
    `- Output: ${ir.output ? `${ir.output.componentName} on ${ir.output.pinId}` : "none detected"}`,
    `- Input: ${ir.input ? `${ir.input.componentName} on ${ir.input.pinId}` : "none detected"}`,
    "",
    "Build with ESP-IDF from this folder:",
    "",
    "```",
    "idf.py set-target " + ir.target,
    "idf.py build",
    "```",
    ""
  ];
  if (ir.drc.issues.length) {
    lines.push("## Design Rule Check", "");
    for (const issue of ir.drc.issues) {
      lines.push(`- ${issue.severity.toUpperCase()}: ${issue.message}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function generatedFirmwareFiles(ir) {
  return [
    {
      path: "CMakeLists.txt",
      content: `cmake_minimum_required(VERSION 3.16)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(${ir.name})
`
    },
    {
      path: "main/CMakeLists.txt",
      content: `idf_component_register(SRCS "app_main.c" INCLUDE_DIRS ".")
`
    },
    {
      path: "main/app_main.c",
      content: generateMainC(ir)
    },
    {
      path: "sdkconfig.defaults",
      content: `CONFIG_COMPILER_OPTIMIZATION_SIZE=y
`
    },
    {
      path: "README.md",
      content: generateReadme(ir)
    },
    {
      path: "robostudio-circuit.json",
      content: ""
    }
  ];
}

export function generateCircuitFirmware(design) {
  const normalized = normalizeCircuitDesign(design);
  const ir = buildCircuitIr(normalized);
  const files = generatedFirmwareFiles(ir).map((file) => ({
    ...file,
    content: file.path === "robostudio-circuit.json"
      ? JSON.stringify(normalized, null, 2)
      : file.content
  }));
  const customFiles = normalized.customCode.files ?? [];
  const byPath = new Map(files.map((file) => [file.path, file]));
  for (const file of customFiles) {
    byPath.set(file.path, { path: file.path, content: file.content, custom: true });
  }
  const mergedFiles = [...byPath.values()].sort((left, right) => left.path.localeCompare(right.path));
  return {
    ir,
    files: mergedFiles,
    ready: Boolean(ir.output) && ir.drc.summary.errors === 0,
    warnings: ir.drc.issues.filter((item) => item.severity !== "error")
  };
}

export function firmwareArchiveName(design) {
  const normalized = normalizeCircuitDesign(design);
  return `${sanitizeIdentifier(normalized.name)}-esp-idf.zip`;
}

export async function createFirmwareProjectZip(design, options = {}) {
  const firmware = generateCircuitFirmware(design);
  if (!firmware.ready && options.allowDrcErrors !== true) {
    throw new Error("Firmware export is blocked until electronics DRC errors are resolved.");
  }
  const zip = new JSZip();
  for (const file of firmware.files) {
    zip.file(file.path, file.content);
  }
  return zip.generateAsync({
    type: options.type ?? "blob",
    compression: "DEFLATE"
  });
}
